FROM docker.io/python:3.10

RUN /bin/bash -c "apt update; \
                  apt install -y wget patch autoconf libtool g++ make"

# create a dedicated user
RUN /bin/bash -c "useradd -m builder"

USER builder
ENV HOME=/home/builder
WORKDIR $HOME

COPY --chown=builder packages/lhapdf $HOME/lhapdf

ENV PREFIX=$HOME/.local
ENV PATH=$PATH:$HOME/.local/bin

RUN /bin/bash -c "cd $HOME/lhapdf; sh install.sh"

# --------------------------------------------------------- #

FROM docker.io/python:3.10-slim

# install further packages to support the workflow
# curl: required by snok/install-poetry@v1
# git: required by actions/checkout@v2
# wget: useful to recursively pull remote resources
RUN /bin/bash -c "apt update; \ 
                  apt install -y curl git wget"

COPY --from=0 /home/builder/.local/bin/ /usr/local/bin/
COPY --from=0 /home/builder/.local/lib/ /usr/local/lib/
COPY --from=0 /home/builder/.local/share/ /usr/local/share/

ENV LD_LIBRARY_PATH=/usr/local/lib/
ENV LHAPDF_DATA_PATH=/usr/local/share/LHAPDF/

RUN /bin/bash -c "lhapdf install NNPDF40_nnlo_as_01180 \
                                 ABMP16_5_nnlo \
                                 ATLASpdf21_T1 \
                                 CT18NNLO \
                                 HERAPDF20_NNLO_EIG \
                                 MSHT20nnlo_as118 \
                                 PDF4LHC21_mc"

ENTRYPOINT /bin/bash
