FROM docker.io/python:3.10

# create a dedicated user
RUN /bin/bash -c "apt update; \
                  apt install -y wget patch autoconf libtool g++ gfortran make \
                  pip install numpy"

COPY packages/lhapdf $HOME/lhapdf
COPY packages/apfel $HOME/apfel
COPY packages/fonlldis $HOME/fonlldis
COPY packages/qcdnum $HOME/qcdnum
COPY packages/xspace-bench $HOME/xspace-bench
# TODO: remove this dirty trick
COPY packages/.backup/ $HOME/.backup

RUN /bin/bash -c "cd lhapdf; sh install.sh"
RUN /bin/bash -c "cd apfel; sh install.sh"
RUN /bin/bash -c "cd fonlldis; sh install.sh"
RUN /bin/bash -c "cd qcdnum; sh install.sh"
RUN /bin/bash -c "cd xspace-bench; sh install.sh"

# --------------------------------------------------------- #

FROM docker.io/python:3.10-slim

ENV LD_LIBRARY_PATH=/usr/local/lib

COPY --from=0 /usr/lib/x86_64-linux-gnu/libquadmath* /usr/lib/x86_64-linux-gnu/
COPY --from=0 /usr/lib/x86_64-linux-gnu/libgfortran* /usr/lib/x86_64-linux-gnu/
COPY --from=0 /usr/local /usr/local
