FROM docker.io/python:3.10

ARG HOME=/root
ARG PREFIX=$HOME/local

# create a dedicated user
RUN /bin/bash -c "apt update; \
                  apt install -y wget patch autoconf libtool g++ gfortran make; \
                  pip install numpy \
                  mkdir $HOME/local"

COPY packages/lhapdf $HOME/lhapdf
COPY packages/apfel $HOME/apfel
COPY packages/qcdnum $HOME/qcdnum
COPY packages/pegasus $HOME/pegasus
# TODO: remove this dirty trick
COPY packages/.backup/ $HOME/.backup

RUN /bin/bash -c "cd $HOME/lhapdf; sh install.sh"
RUN /bin/bash -c "cd $HOME/apfel; sh install.sh"
RUN /bin/bash -c "cd $HOME/qcdnum; sh install.sh"
RUN /bin/bash -c "cd $HOME/pegasus; sh install.sh"

# --------------------------------------------------------- #

FROM docker.io/python:3.10-slim

RUN /bin/bash -c "apt update; \
                  apt install -y git curl wget"

COPY --from=0 /usr/lib/x86_64-linux-gnu/libquadmath* /usr/lib/x86_64-linux-gnu/
COPY --from=0 /usr/lib/x86_64-linux-gnu/libgfortran* /usr/lib/x86_64-linux-gnu/
COPY --from=0 /usr/local /usr/local
COPY --from=0 /root/local/bin/ /usr/local/bin/
COPY --from=0 /root/local/lib/ /usr/local/lib/
COPY --from=0 /root/local/share/ /usr/local/share/

ENV LD_LIBRARY_PATH=/usr/local/lib/
ENV LHAPDF_DATA_PATH=/usr/local/share/LHAPDF/

ENTRYPOINT /bin/bash
