FROM docker.io/python:3.10

# create a dedicated user
RUN /bin/bash -c "apt update; \
                  apt install -y wget patch autoconf libtool g++ gfortran make; \
                  pip install numpy"

COPY packages/lhapdf $HOME/lhapdf
COPY packages/apfel $HOME/apfel
COPY packages/qcdnum $HOME/qcdnum
COPY packages/pegasus $HOME/pegasus
# TODO: remove this dirty trick
COPY packages/.backup/ $HOME/.backup

RUN /bin/bash -c "cd $HOME/lhapdf; sh install.sh"
RUN /bin/bash -c "cd $HOME/apfel; sh install.sh"
RUN /bin/bash -c "cd $HOME/qcdnum; sh install.sh"
RUN /bin/bash -c "cd $HOME/pegasus; sh install.sh"

# --------------------------------------------------------- #

FROM docker.io/python:3.10-slim

RUN /bin/bash -c "apt update; \
                  apt install -y git curl wget"

COPY --from=0 /usr/lib/x86_64-linux-gnu/libquadmath* /usr/lib/x86_64-linux-gnu/
COPY --from=0 /usr/lib/x86_64-linux-gnu/libgfortran* /usr/lib/x86_64-linux-gnu/
COPY --from=0 /usr/local /usr/local
ENV LD_LIBRARY_PATH=/usr/local/lib/

ENTRYPOINT /bin/bash
