name: Publish Containers

on:
  push:
    tags:
      - "*"

jobs:
  publish:
    name: Build and push image
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package: ["lhapdf", "bench-evol", "bench-dis"]

    steps:
      - uses: actions/checkout@v2
      - name: Buildah Build Image 🛠
        id: build
        uses: redhat-actions/buildah-build@v2
        with:
          image: ghcr.io/n3pdf/${{ matrix.package }}
          tags: v2 ${{ github.ref_name }}
          containerfiles: |
            ./containers/${{ matrix.package }}/Containerfile
          oci: true
      - name: Push To GHCR ⬆
        uses: redhat-actions/push-to-registry@v2
        id: push
        with:
          image: ${{ steps.build.outputs.image }}
          tags: ${{ steps.build.outputs.tags }}
          registry: ghcr.io/${{ github.repository_owner }}
          username: ${{ github.actor }}
          password: ${{ github.token }}
          extra-args: |
            --disable-content-trust
      - name: Echo outputs
        run: |
          echo "${{ toJSON(steps.push.outputs) }}"
